sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t iammatthewward/dr -f Dockerfile.dev .

script:
  - docker run -e CI=true iammatthewward/dr npm run test -- --coverage



